=== MCC-anonymous/xml/resume.dtd
<DOCTYPE resume[
 <!ELEMENT resume(personal_details,skills,projects)>
 <!ELEMENT personal_details(name,email,phone,city)>
 <!ELEMENT name (#PCDATA)>
 <!ELEMENT email (#PCDATA)>
 <!ELEMENT phone (#PCDATA)>
 <!ELEMENT city  (#PCDATA)>
 <!ELEMENT skills(s)>
 <!ELEMENT s (#PCDATA)>
 <!ELEMENT projects(p)>
 <!ELEMENT p (#PCDATA)>
 
]>

=== MCC-anonymous/xml/exp4.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE resume SYSTEM "resume.dtd">

<resume>
 <personal_details>
    <name>ABC</name>
    <email>abc@ms3.com</email>
    <phone>9876543210</phone>
    <city>chandigarh</city>
 </personal_details>
 <skills>
  <s>C/C++</s>
  <s>Java</s>
  <s>AWS</s>
 </skills>
 <projects>
  <p>IncomeTax Calculator</p>
  <p>Hospital Management System</p>
  <p> Mangalyaan</p>
 </projects>
</resume>
